#! /bin/bash 
set -e

cd "$(dirname "$0")"

docker build -t anvil-runtime-tests -f Dockerfile ../..

# Make the docker volume paths work on Windows
export MSYS_NO_PATHCONV=1

docker run --rm -it -v "$(pwd)/apps:/runtime/server/app-server/apps" \
                    -v "$(pwd)/configs:/runtime/server/app-server/configs" \
                    -v "$(pwd)/py_tests:/runtime/server/app-server/py_tests" \
                   anvil-runtime-tests bash -c 'pytest' 



#  -v "./anvil.conf.yaml:/runtime/server/app-server/test-files/anvil.conf.yaml" \
                   